version: '3.1'
services:
  db:
    image: mysql
    container_name: eBanking-backend
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3309:3306"
    volumes:
      - ./storage:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: E-BANK